services:
    buyer-ui:
        container_name: buyer-ui
        build:
            context: ./buyer-ui
        volumes:
            - ./buyer-ui:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        env_file:
            - ./buyer-ui/.env
        networks:
            - tientv-ecommerce

    seller-ui:
        container_name: seller-ui
        build:
            context: ./seller-ui
        volumes:
            - ./seller-ui:/app
            - /app/node_modules
        ports:
            - "3001:3000"
        env_file:
            - ./seller-ui/.env
        networks:
            - tientv-ecommerce

    admin-ui:
        container_name: admin-ui
        build:
            context: ./admin-ui
        volumes:
            - ./admin-ui:/app
            - /app/node_modules
        ports:
            - "3002:3000"
        env_file:
            - ./admin-ui/.env
        networks:
            - tientv-ecommerce
    # =====================================================================================================
    #                                           | SQL Server |
    # =====================================================================================================
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
        SA_PASSWORD: tientv@123
        ACCEPT_EULA: "Y"
        ports:
        - "1433:1433"
        networks:
        - tientv-ecommerce
    # =====================================================================================================
    #                                     | FUSIONAUTH (AUTH SERVICE) |
    # =====================================================================================================
    fusionauth:
        image: fusionauth/fusionauth-app
        environment:
            DATABASE_URL: jdbc:sqlserver://mssql:1433;databaseName=fusionauth
            DATABASE_USERNAME: sa
            DATABASE_PASSWORD: tientv@123
            FUSIONAUTH_MEMORY: 512M
        depends_on:
            - mssql
        networks:
            - tientv-ecommerce
    # =====================================================================================================
    #                                           | USER SERVICE |
    # =====================================================================================================
    user-service:
        build:
            context: ./user-service
        environment:
            DB_URL: jdbc:sqlserver://mssql:1433;databaseName=ecom_users
            DB_USERNAME: sa
            DB_PASSWORD: tientv@123
        depends_on:
            - mssql
        networks:
            - tientv-ecommerce
    # =====================================================================================================
    #                                           | API GATEWAY |
    # =====================================================================================================
    api-gateway:
        container_name: api-gateway
        build:
            context: ./api-gateway
        ports:
            - "8088:8080"
        depends_on:
            - user-service
            - fusionauth
        networks:
            - tientv-ecommerce

networks:
    tientv-ecommerce:
        driver: bridge
