services:
    buyer-ui:
        container_name: buyer-ui
        build:
            context: ./buyer-ui
        volumes:
            - ./buyer-ui:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        env_file:
            - ./buyer-ui/.env
        networks:
            - tientv-ecommerce

    seller-ui:
        container_name: seller-ui
        build:
            context: ./seller-ui
        volumes:
            - ./seller-ui:/app
            - /app/node_modules
        ports:
            - "3001:3000"
        env_file:
            - ./seller-ui/.env
        networks:
            - tientv-ecommerce

    admin-ui:
        container_name: admin-ui
        build:
            context: ./admin-ui
        volumes:
            - ./admin-ui:/app
            - /app/node_modules
        ports:
            - "3002:3000"
        env_file:
            - ./admin-ui/.env
        networks:
            - tientv-ecommerce

networks:
    tientv-ecommerce:
        driver: bridge
