version: "3.9"
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "tientv@123"
        ports:
            - "1433:1433"

    ecom-gateway:
        build: ./ecom-gateway
        ports:
            - "8080:8080"
        volumes:
            - ./ecom-gateway:/app
            - /app/target
        depends_on:
            - sqlserver

    ecom-user-service:
        build: ./ecom-user-service
        ports:
            - "8081:8080"
        volumes:
            - ./ecom-user-service:/app
            - /app/target
        env_file:
            - ./ecom-user-service/.env
        depends_on:
            - sqlserver

    ecom-product-service:
        build: ./ecom-product-service
        ports:
            - "8082:8080"
        volumes:
            - ./ecom-product-service:/app
            - /app/target
        env_file:
            - ./ecom-product-service/.env
        depends_on:
            - sqlserver

    ecom-buyer-ui:
        build: ./ecom-buyer-ui
        ports:
            - "3001:3000"
        env_file:
            - ./ecom-buyer-ui/.env
        volumes:
            - ./ecom-buyer-ui:/app
            - /app/node_modules

networks:
    default:
        driver: bridge
