version: "3.9"
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "tientv@123"
        ports:
            - "1433:1433"
        volumes:
            - ./docker/sqlserver:/var/opt/mssql
            - ./docker/sqlserver/init-multiple-db.sql:/docker-entrypoint-initdb.d/init-multiple-db.sql

    ecom-gateway:
        build: ./ecom-gateway
        ports:
            - "8080:8080"
        volumes:
            - ./ecom-gateway:/app
            - /app/target
        environment:
            SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=ecom_users
            SPRING_DATASOURCE_USERNAME: sa
            SPRING_DATASOURCE_PASSWORD: tientv@123
        depends_on:
            - sqlserver

    ecom-user-service:
        build: ./ecom-user-service
        ports:
            - "8081:8080"
        volumes:
            - ./ecom-user-service:/app
            - /app/target
        environment:
            SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=ecom_users
            SPRING_DATASOURCE_USERNAME: sa
            SPRING_DATASOURCE_PASSWORD: tientv@123
        depends_on:
            - sqlserver

    ecom-product-service:
        build: ./ecom-product-service
        ports:
            - "8082:8080"
        volumes:
            - ./ecom-product-service:/app
            - /app/target
        environment:
            SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=ecom_products
            SPRING_DATASOURCE_USERNAME: sa
            SPRING_DATASOURCE_PASSWORD: tientv@123
        depends_on:
            - sqlserver

    ecom-buyer-ui:
        build: ./ecom-buyer-ui
        ports:
            - "3001:3000"
        env_file:
            - ./ecom-buyer-ui/.env
        volumes:
            - ./ecom-buyer-ui:/app
            - /app/node_modules

networks:
    default:
        driver: bridge
