services:
    user-ui:
        build:
            context: ./user-ui
        volumes:
            - ./user-ui:/app
            - /app/node_modules
        ports:
            - "3001:3000"
        environment:
            - NODE_ENV=development

    admin-ui:
        build:
            context: ./admin-ui
        volumes:
            - ./admin-ui:/app
            - /app/node_modules
        ports:
            - "3002:3000"
        environment:
            - NODE_ENV=development
