server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
                -   id: user-service
                    uri: http://user-service:8080
                    predicates:
                        - Path=/api/auth/**
                -   id: product-service
                    uri: http://product-service:8080
                    predicates:
                        - Path=/api/product/**
                -   id: order-service
                    uri: http://order-service:8080
                    predicates:
                        - Path=/api/order/**
                # Add route cho các service

            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
