server:
    port: 8080

spring:
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: user-route
                          uri: ${http://ecom-user-service:8080}
                          predicates:
                              - Path=/api/users/**

    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
